services:
  goaffpro:
    build: .
    container_name: goaffpro-rechnungen
    ports:
      - "8090:8080"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./config/config.properties:/app/config/config.properties
      - ./docker-data/exports:/app/exports
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
