services:
  goaffpro:
    build: .
    container_name: goaffpro-rechnungen
    ports:
      - "8090:8080"
    volumes:
      - goaffpro-config:/app/config
      - /volume1/docker/goaffpro_rechnungen/export:/app/exports
    environment:
      - TZ=Europe/Berlin
      - GOAFFPRO_API_KEY=${GOAFFPRO_API_KEY:-}
      - GOAFFPRO_SMTP_HOST=${GOAFFPRO_SMTP_HOST:-}
      - GOAFFPRO_SMTP_USERNAME=${GOAFFPRO_SMTP_USERNAME:-}
      - GOAFFPRO_SMTP_PORT=${GOAFFPRO_SMTP_PORT:-}
      - GOAFFPRO_SMTP_TLS=${GOAFFPRO_SMTP_TLS:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
    restart: unless-stopped

volumes:
  goaffpro-config:
