importBelegePath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/importBelege
importZahlungenPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/importZahlungen
importZahlungenBillbeePath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/importZahlungenBillbee
processedPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/processed
exportPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/export
processPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/process
belegJahr=2025
goaffproAPIKey=962a6e67f4f427fc710ded0b94ebbff40d7919548a2cbeccf9981a39aa3bff13
lastImportedComission=1994162
lastImportedComission_setzen_wenns_losgeht=1772181 1668606 1780342 1780357 1784883 1811346 - 1813970 - 1827041 - 1864428 1883352 1929847 1939943 - 1944773-1994162
