importBelegePath=C:/Users/nluenzer/IdeaProjects/untitled/src/main/resources/importBelege

processedPath=C:/Users/nluenzer/IdeaProjects/untitled/src/main/resources/processed
exportPath=C:/Users/nluenzer/IdeaProjects/untitled/src/main/resources/export
processPath=C:/Users/nluenzer/IdeaProjects/untitled/src/main/resources/process