importBelegePath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/importBelege
importZahlungenPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/importZahlungen
importZahlungenBillbeePath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/importZahlungenBillbee
processedPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/processed
exportPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/export
processPath=/Users/nicolas/IdeaProjects/java_pds_converter/src/main/resources/process
belegJahr=2025
goaffproAPIKey=91bdb6e219f5b9ffeff929077b4badd5d7a26c235c672e20285885835683b845
lastImportedComission=2565325
lastImportedComission_setzen_wenns_losgeht= - 2103705 -2167905-2190357-2230376-2336836-2421355-2497986-2565325

lastImportedComissionHistory=2103705,2167905,2190357,2230376,2336836,2421355,2497986,2565325
